trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      echo Hello world

      git push https://omaralbakri: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@github.com/omaralbakri/TestSync.git HEAD:main
