trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      echo Hello world
      echo Hello world2
      git push https://suhaibj21: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@github.com/suhaibj21/alttask.git HEAD:main 
