trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  fetchDepth: 0

- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      echo Hello world
      echo Hello world2
      git push https://suhaibj21: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@github.com/suhaibj21/alttask.git HEAD:main 
