trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      echo Hello world
      echo Hello world2
      git push https://suhaibj21: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@github.com/suhaibj21/alttask.git HEAD:main --force

